include(8_1QPainterBasicWidget/8_1QPainterBasicWidget.pri)
include(8_2PaintPathWidget/8_2PaintPathWidget.pri)
include(8_3ViewportWidget/8_3ViewportWidget.pri)
include(8_3PlotWidget/8_3PlotWidget.pri)
